spring.application.name=client

server.port=8081

#spring.datasource.url=jdbc:mysql://db-client:3307/clinical_db
spring.datasource.url=jdbc:mysql://localhost:3307/clinical_db
spring.datasource.username=root
spring.datasource.password=3J^,+VGAg64]GpDaWx8V

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.jdbc.lo.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#RabbitMQ
spring.rabbitmq.addresses=amqps://kggjrzik:pgNGpQaMePzMKdgSG2ENa0DsohphUpRz@rabbit.lmq.cloudamqp.com/kggjrzik
broker.queue.email.name=default.email

#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daniela.mmota@sempreceub.com
spring.mail.password=frBl7ya03RUPgeN
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true